pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls,name="admin-site"),
    path("pos/", include("posApp.urls")),
    path("", RedirectView.as_view(url="pos")),
    path('login/', RedirectView.as_view(url="/pos/login"),name="redirect-login"),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "JULLIVAM HARDWARE"
admin.site.site_title = "POS"
admin.site.index_title = 'Welcome'

posApp/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('redirect-admin', RedirectView.as_view(url="/admin"),name="redirect-admin"),
    path('', views.home, name="home-page"),
    path('login', auth_views.LoginView.as_view(template_name = 'posApp/login.html',redirect_authenticated_user=True), name="login"),
    path('userlogin', views.login_user, name="login-user"),
    path('logout', views.logoutuser, name="logout"),
    path('category', views.category, name="category-page"),
    path('manage_category', views.manage_category, name="manage_category-page"),
    path('save_category', views.save_category, name="save-category-page"),
    path('delete_category', views.delete_category, name="delete-category"),
    path('products', views.products, name="product-page"),
    path('products/update-count/<int:product_id>/', views.add_to_stock, name="add_to_stock"),
    path('manage_products', views.manage_products, name="manage_products-page"),
    path('save_product', views.save_product, name="save-product-page"),
    path('delete_product', views.delete_product, name="delete-product"),
    path('pos', views.pos, name="pos-page"),
    path('checkout-modal', views.checkout_modal, name="checkout-modal"),
    path('save-pos', views.save_pos, name="save-pos"),
    path('sales', views.salesList, name="sales-page"),
    path('receipt', views.receipt, name="receipt-modal"),
    path('delete_sale', views.delete_sale, name="delete-sale"),
    path('reconsile/', views.returns, name="reconsile"),
    path("notify/", views.notify, name="notify"),
    path("customers/", views.customers, name="customers"),
    path('customers/<slug>/delete/', views.CustomerDeleteView.as_view(), name="delete_customer"),
    path('customers/<slug:slug>/edit', views.edit_cusomer, name="edit_customer"),
    path('customers/<slug:slug>/history/', views.customer_history, name="customer_history"),
    path('sales/profits/', views.overall_profis_and_loss, name="overall_profis_and_loss"),
    path('sales/profits/<int:product_id>/', views.product_profit_margins, name='profit_margins'),

    # path('employees', views.employees, name="employee-page"),
    # path('manage_employees', views.manage_employees, name="manage_employees-page"),
    # path('save_employee', views.save_employee, name="save-employee-page"),
    # path('delete_employee', views.delete_employee, name="delete-employee"),
    # path('view_employee', views.view_employee, name="view-employee-page"),
]

posApp/models.py
from datetime import datetime
from unicodedata import category
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
from datetime import datetime

# Create your models here.

# class Employees(models.Model):
#     code = models.CharField(max_length=100,blank=True) 
#     firstname = models.TextField() 
#     middlename = models.TextField(blank=True,null= True) 
#     lastname = models.TextField() 
#     gender = models.TextField(blank=True,null= True) 
#     dob = models.DateField(blank=True,null= True) 
#     contact = models.TextField() 
#     address = models.TextField() 
#     email = models.TextField() 
#     department_id = models.ForeignKey(Department, on_delete=models.CASCADE) 
#     position_id = models.ForeignKey(Position, on_delete=models.CASCADE) 
#     date_hired = models.DateField() 
#     salary = models.FloatField(default=0) 
#     status = models.IntegerField() 
#     date_added = models.DateTimeField(default=timezone.now) 
#     date_updated = models.DateTimeField(auto_now=True) 

    # def __str__(self):
    #     return self.firstname + ' ' +self.middlename + ' '+self.lastname + ' '

def avatar_path(instance, filename):
    return f"avatars/{instance.customer_id}/{filename}"

class TrustedCustomerProfile(models.Model):
    name = models.CharField(max_length=65)
    email = models.EmailField(null=True, blank=True)
    avatar = models.ImageField(upload_to=avatar_path, default="ava.jpg", blank=True)
    slug = models.SlugField(unique=True, blank=True, verbose_name="Customer Id")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = '-'.join((slugify(self.name), slugify(datetime.now())))
        return super(TrustedCustomerProfile, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"

class Category(models.Model):
    name = models.TextField()
    description = models.TextField()
    status = models.IntegerField(default=1) 
    date_added = models.DateTimeField(default=timezone.now) 
    date_updated = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = verbose_name

def product_image_path(instance, filename):
    return f"product/{instance.code}/{filename}"

class Products(models.Model):
    code = models.CharField(max_length=100)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.TextField()
    description = models.TextField()
    buying_price = models.FloatField(default=0)
    price = models.FloatField(default=0)
    status = models.IntegerField(default=1)
    date_added = models.DateTimeField(default=timezone.now) 
    date_updated = models.DateTimeField(auto_now=True)
    bought_count = models.IntegerField(default=0)
    product_count = models.IntegerField(default=10)
    measurement_units = models.CharField(max_length=55, default="units")
    minimum_stock = models.IntegerField(default=1, help_text="warning, low stock!!!")
    image = models.ImageField(default="default-image.jpg")

    def __str__(self):
        return self.code + " - " + self.name
    
    @property
    def is_low_stock(self):
        if self.minimum_stock >= self.product_count:
            return True
        else:
            return False
            
    class Meta:
        verbose_name = "Product"
        verbose_name_plural = verbose_name

class Sales(models.Model):
    code = models.CharField(max_length=100)
    sub_total = models.FloatField(default=0)
    grand_total = models.FloatField(default=0)
    tax_amount = models.FloatField(default=0)
    tax = models.FloatField(default=0)
    tendered_amount = models.FloatField(default=0)
    amount_change = models.FloatField(default=0)
    date_added = models.DateTimeField(default=timezone.now) 
    date_updated = models.DateTimeField(auto_now=True)
    customer = models.ForeignKey(TrustedCustomerProfile, on_delete=models.CASCADE, related_name="customer", null=True, blank=True)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = "Sales"
        verbose_name_plural = verbose_name

class salesItems(models.Model):
    sale_id = models.ForeignKey(Sales, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Products,on_delete=models.CASCADE)
    price = models.FloatField(default=0)
    qty = models.FloatField(default=0)
    total = models.FloatField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Sales Items"
        verbose_name_plural = verbose_name


class ProductReturns(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name="product")
    return_quantity = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Product Returns"
        verbose_name_plural = verbose_name

class Notify(models.Model):
    title = models.CharField(max_length=155)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name="product_notify")
    resolved = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Low Stock Notifications"
        verbose_name_plural = verbose_name

posApp/forms.py
from django import forms
from posApp.models import ProductReturns, TrustedCustomerProfile


class ReturnsForm(forms.ModelForm):
    class Meta:
        model = ProductReturns
        fields = ["product", "return_quantity"]
        widgets = {
            "product": forms.Select(attrs={"style": "width:100%"})
        }

class AddCustomerForm(forms.ModelForm):
    class Meta:
        model = TrustedCustomerProfile
        exclude = ["slug",]

posApp/templates/posApp/add_to_sock.html
{% extends "base.html" %}

{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0">Add to {{product.code}}-{{prod.name}} </h4>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
            Current Count: {{prod.product_count}}
        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="plus_number" class="form-label">Add Products</label>
                <input type="number" class="form-control" name="plus_number" id="plus_number">
              </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

posApp/templates/posApp/category.html
{% extends "base.html" %} 
{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0">Category List</h4>
            <div class="text-start">
                <button class="btn btn-primary bg-gradient btn-sm rounded-0" id="create_new"><i class="mdi mdi-plus"></i><span> Add New</span></button>
            </div>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <colgroup>
                    <col width="5%">
                    <col width="30%">
                    <col width="30%">
                    <col width="15%">
                    <col width="20%">
                </colgroup>
                <thead>
                    <tr>
                        <th class="text-center py-1">#</th>
                        <th class="text-center py-1">category Name</th>
                        <th class="text-center py-1">Description</th>
                        <th class="text-center py-1">Status</th>
                        <th class="text-center py-1">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cat in category %}
                    <tr>
                        <td class="px-2 py-1 text-center">{{ cat.id }}</td>
                        <td class="px-2 py-1 text-start">{{ cat.name }}</td>
                        <td class="px-2 py-1 text-start">{{ cat.description }}</td>
                        <td class="px-2 py-1 text-center">
                            {% if cat.status == 1 %}
                            <span class="badge bg-primary rounded-pill px-3">Active</span> {% else %}
                            <span class="badge bg-secondary rounded-pill px-3">Inactive</span> {% endif %}
                        </td>
                        <td class="px-2 py-1 text-center">
                            <button class="mdc-button mdc-button--raised p-1 icon-button filled-button--light mdc-ripple-upgraded edit-data" type="button" data-id="{{ cat.pk }}" title="Edit">
                                <i class="material-icons mdc-button__icon">edit</i>
                            </button>
                            <button class="mdc-button mdc-button--raised p-1 icon-button filled-button--danger mdc-ripple-upgraded delete-data" type="button" data-id="{{ cat.pk }}" title="Delete">
                                <i class="material-icons mdc-button__icon">deleteoutline</i>
                            </button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock pageContent %} 
{% block ScriptBlock %}
<script>
    $(function() {
        $('#create_new').click(function() {
            uni_modal("Add New Category", "{% url 'manage_category-page' %}")
        })
        $('.edit-data').click(function() {
            uni_modal("Edit Category", "{% url 'manage_category-page' %}?id=" + $(this).attr('data-id'))
        })
        $('.delete-data').click(function() {
            _conf("Are you sure to delete this Category?", "delete_category", [$(this).attr('data-id')])
        })
    })

    function delete_category($id) {
        start_loader();
        $.ajax({
            headers: {
                "X-CSRFToken": '{{csrf_token}}'
            },
            url: "{% url 'delete-category' %}",
            method: "POST",
            data: {
                id: $id
            },
            dataType: "json",
            error: err => {
                console.log(err)
                alert_toast("An error occured.", 'error');
                end_loader();
            },
            success: function(resp) {
                if (typeof resp == 'object' && resp.status == 'success') {
                    location.reload();
                } else {
                    alert_toast("An error occured.", 'error');
                    end_loader();
                }
            }
        })
    }
</script>

{% endblock ScriptBlock %}

posApp/templates/posApp/checkout.html
{% load humanize %}
<div class="container-fluid">
    <form action="" id="checkout-form">
        <div class="form-group mb-3">
            <label for="payable_amount" class="control-label">Payable Amount</label>
            <input type="text" id="payable_amount" class="form-control form-control-lg rounded-0 text-end" value="{{ grand_total|intcomma }}" required>
        </div>
        <div class="form-group mb-3">
            <label for="tendered_amount" class="control-label">Amount Tendered</label>
            <input type="number" step="any" id="tendered_amount" class="form-control form-control-lg rounded-0 text-end" value="0" required>
        </div>
        <div class="form-group mb-3">
            <label for="payment_change" class="control-label">Change</label>
            <input type="text" id="payment_change" class="form-control form-control-lg rounded-0 text-end" value="{{ 0|intcomma }}" required disabled>
        </div>
    </form>
</div>
<script>
    $(function() {
        $('#tendered_amount').on('input keypress keyup keydown', function() {
            var tendered_amount = $('#tendered_amount').val()
            var payable = $('#payable_amount').val()
            tendered_amount = tendered_amount.replace(/,/gi, '')
            payable = payable.replace(/,/gi, '')
            var change = 0
            tendered_amount = tendered_amount > 0 ? tendered_amount : 0;
            $('[name="tendered_amount"]').val(tendered_amount)
            change = parseFloat(tendered_amount) - parseFloat(payable)
            console.log(tendered_amount, payable)
            $('#payment_change').val(parseFloat(change).toLocaleString('en-US'))
            $('[name="amount_change"]').val(change)

        })
        $('#checkout-form').submit(function(e) {
            e.preventDefault();
            if ($('[name="amount_change"]').val() < 0) {
                alert("Tendered Amount is lower that Payable Amount")
                return false;
            }
            $('#pos-form').submit()
        })
    })
</script>

posApp/templates/posApp/customer_history.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0"> {{customer.name}} </h4>
            <a href="{% url 'customers' %}" class="btn btn-outline-success" type="btn">Back to customers</a>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
        <div class="table-responsive">
            <table class="table table-striped table-bordered caption-top" id="returns">
                <caption>Cusomer History</caption>
                <thead>
                    <tr>
                        <th class="text-center py-1">Sales Id</th>
                        <th class="text-center py-1">Product Code</th>
                        <th class="text-center py-1">Product Name</th>
                        <th class="text-center py-1">Bought Quantity</th>
                        <th class="text-center py-1">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items_history %}
                    <tr>
                        <td class="px-2 py-1 text-start">{{item.sale_id.code}}</td>
                        <td class="px-2 py-1 text-start">{{ item.product_id.code }}</td>
                        <td class="px-2 py-1 text-start">{{ item.product_id.name }}</td>
                        <td class="px-2 py-1 text-start">{{ item.qty|intcomma }}</td>
                        <td class="px-2 py-1 text-start">{{ item.total }}</td>
                        <td class="px-2 py-1 text-start">{{ item.created|naturaltime }}</td>                    
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    {{item.sale_id.cusomer.name|title}} History
                </tfoot>
            </table>
        </div>
    </div>
</div>

{% endblock pageContent %}

posApp/templates/posApp/customers.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0">Customers Profiles</h4>
            <div class="text-start">
                <button class="btn btn-primary bg-gradient btn-sm rounded-0" data-bs-toggle="modal" data-bs-target="#costomerModel"><i class="mdi mdi-plus"></i><span> Add New Customer </span></button>
            </div>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
        <div class="table-responsive">
            <table class="table table-striped table-bordered caption-top" id="returns">
                <caption>Customers</caption>
                <thead>
                    <tr>
                        <th class="text-center py-1">#</th>
                        <th class="text-center py-1">Email</th>
                        <th class="text-center py-1">Customer Id</th>
                        <th class="text-center py-1">Date</th>
                        <th class="text-center py-1">Actions</th>                        
                    </tr>
                </thead>
                <tbody>
                    {% for customer in customers %}
                    <tr>
                        <td class="px-2 py-1 text-start">
                            <div class="d-flex align-items-center">
                                <img src="{{ customer.avatar.url }}" alt="avatar"  style="width: 45px; height: 45px" class="rounded-circle"/>
                                <div class="ms-3">
                                    <p class="fw-bold mb-1"> {{ customer.name }}</p>
                                </div>
                            </div>
                        </td>
                        <td class="px-2 py-1 text-start">{{ customer.email }}</td>
                        <td class="px-2 py-1 text-start">{{ customer.id }}</td>
                        <td class="px-2 py-1 text-start">{{ customer.created|naturalday }}</td> 
                        <td class="px-2 py-1 text-start">
                            <a href="{% url 'customer_history' customer.slug %}">History</a>
                            <a href="{% url 'edit_customer' customer.slug %}" class="ms-2">Edit</a>
                            <a href="{% url 'delete_customer' customer.slug %}" class="ms-2">Delete</a>
                        </td>                     
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% comment %} modal start {% endcomment %}
<div class="modal fade" id="costomerModel" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="costomerModellable" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="costomerModellable">Add New Customer</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="modal-body w-100">
                {{add_form|crispy}}
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
        <script>
            $(document).ready(function() {
                $("#id_product").select2(
                    {
                        dropdownParent: $("#costomerModel"),
                        theme: "classic"
                    }
                );
            });
        </script>
      </div>
    </div>
  </div>
{% comment %} modal end  {% endcomment %}

{% endblock pageContent %}

posApp/templates/posApp/delete_customer.html
{% extends 'base.html' %}
{% load humanize %}

{% block pageContent %}

<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <form method="post">
            {% csrf_token %}
            <h2>Delete Customer</h2>
            <p>Are you sure that you want to delete "{{customer.name|title}}"?</p>
            <p class="form-buttons text-center">
                <input type="submit" class="btn btn-outline-primary" value="Delete">
                <a href="{% url 'customers' %}" class="btn btn-outline">Cancel</a>
            </p>
        </form>
    </div>
</div>

{% endblock %}

posApp/templates/posApp/home.html
{% extends "base.html" %} 
{% load humanize %} {% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">
        <div class="d-flex justify-content-between">
            <h4 class="card-title mb-0">Dashboard</h4>
            <h6 class="card-title m-0"> {% now "jS F Y" %} </h6>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <hr class="w-100">
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--success">
        <div class="card-inner">
            <a href="{% url 'category-page' %}" class="text-decoration-none">
                <h5 class="card-title">Categories</h5>
                <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ categories|intcomma }}</h5>
                <p class="tx-12 text-muted">Categories count</p>
                <div class="card-icon-wrapper">
                    <i class="material-icons">list</i>
                </div>
            </a>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--primary">
        <div class="card-inner">
            <a href="{% url 'product-page' %}">
                <h5 class="card-title">Products</h5>
                <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ products|intcomma }}</h5>
                <p class="tx-12 text-muted">The Count of all your products</p>
                <div class="card-icon-wrapper">
                    <i class="material-icons">label</i>
                </div>
            </a>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--info">
        <div class="card-inner">
            <h5 class="card-title">Today's Transactions</h5>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">{{ transaction|intcomma }}</h5>
            <p class="tx-12 text-muted">Total transactions you did today</p>
            <div class="card-icon-wrapper">
                <i class="material-icons">receipt</i>
            </div>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-3-desktop mdc-layout-grid__cell--span-3-tablet">
    <div class="mdc-card info-card info-card--warning">
        <div class="card-inner">
            <a href="{% url 'sales-page' %}" class="text-decoration-none">
                <h5 class="card-title">Today's Sales</h5>
                <h5 class="font-weight-light pb-2 mb-1 border-bottom">Ksh. {{ total_sales|intcomma }}</h5>
                <p class="tx-12 text-muted">Total sales for today</p>
                <div class="card-icon-wrapper">
                    <i class="mdi mdi-cash-multiple"></i>
                </div>
            </a>
        </div>
    </div>
</div>
{% endblock pageContent %}

posApp/templates/posApp/notify.html
{% extends "base.html" %}
{% load humanize %}
{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0">Low stock</h4>
            <div class="text-start">
                <button class="btn btn-primary bg-gradient btn-sm rounded-0" id="create_new"><i class="mdi mdi-plus"></i><span> button</span></button>
            </div>
        </div>
    </div>
</div>
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card">

        <ul class="list-group list-group-light mb-3">
            {% for n in nots %}
              <li class="list-group-item">
                    <h5 class="fw-bold">{{n.title}}</h5>
                    <p class="text-muted mb-2 fw-bold">{{n.created|naturaltime}}</p>
                    <p class="text mb-0">
                        In Stock: {{n.product.product_count}} {{n.product.measurement_units}}{{n.product.product_count|pluralize}} | Minimum Stock: {{n.product.minimum_stock}} {{n.product.measurement_units}}{{n.product.minimum_stock|pluralize}}
                    </p>
                </li>
            {% empty %}
            <div class="alert alert-secondary">
                <p>There are no noificaions at the moment</p>
            </div>
            {% endfor %}
          </ul>
    </div>
</div>
{% endblock %}